---
language: ruby
sudo: false
cache: bundler
bundler_args: --without benchmarks tools
script:
  - bundle exec rake spec
rvm:
  - 2.2
  - 2.3.0
  - 2.4.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
